# Generated from aliases.sh -- do not edit manually
Bash-Alias .. 'cd ../ @args'
Bash-Alias ... 'cd ../../ @args'
Bash-Alias .... 'cd ../../../ @args'
Bash-Alias ..... 'cd ../../../../ @args'
Bash-Alias 7zc '7z a -mx=9 @args'
Bash-Alias acp 'advcp -gv @args'
Bash-Alias amv 'advmv -gv @args'
Bash-Alias cat 'bat @args'
Bash-Alias cdx 'cd $(xplr) @args'
Bash-Alias cpa '"$CLIPPASTE" @args'
Bash-Alias ccp '"$CLIPCOPY" @args'
Bash-Alias cp 'cp -irv @args'
Bash-Alias diff 'diff --color=auto @args'
Bash-Alias ez 'eza -Ah -s=extension --group-directories-first --icons @args'
Bash-Alias ezl 'eza -AhlT -L=1 -s=extension --group-directories-first --icons --git --git-ignore @args'
Bash-Alias ezr 'eza -AhlR -L=2 -s=extension --group-directories-first --icons --git --git-ignore @args'
Bash-Alias ezt 'eza -ahlT -L=2 -s=extension --group-directories-first --icons --git --git-ignore @args'
Bash-Alias fd 'fd -H @args'
Bash-Alias fdir 'find . -type d -name @args'
Bash-Alias ffil 'find . -type f -name @args'
Bash-Alias grep 'grep --color=auto @args'
Bash-Alias la 'ez @args'
Bash-Alias ll 'ezl @args'
Bash-Alias lr 'ezr @args'
Bash-Alias lt 'ezt @args'
Bash-Alias ldir 'ls -d */ @args'
Bash-Alias ln 'ln -sfnv @args'
Bash-Alias logout 'sudo pkill -u \$USER @args'
Bash-Alias ls 'ls --color=auto @args'
Bash-Alias lsa 'lsd -A --group-dirs first --classify @args'
Bash-Alias lso 'lsd -A --group-dirs first --classify --recursive --depth=2 @args'
Bash-Alias lsl 'lsd -A --group-dirs first --classify -l @args'
Bash-Alias md 'mkdir -p @args'
Bash-Alias mv 'mv -iv @args'
Bash-Alias open 'xdg-open @args'
Bash-Alias rm 'rm -irv @args'
Bash-Alias rmf 'rm -rf @args'
Bash-Alias q 'exit @args'
Bash-Alias g 'git @args'
Bash-Alias ga 'git add @args'
Bash-Alias gaa 'git add --all @args'
Bash-Alias gbrr 'git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format=''%(refname:short)'' @args'
Bash-Alias gc 'git commit -m @args'
Bash-Alias gca 'git commit --all -m @args'
Bash-Alias gcam 'git commit --all --message @args'
Bash-Alias gcma 'git commit --amend -m @args'
Bash-Alias gcman 'git commit --amend --no-edit @args'
Bash-Alias gcmn 'git add . && git commit --amend --no-edit @args'
Bash-Alias gcl 'git config --list @args'
Bash-Alias gcp 'git cherry-pick @args'
Bash-Alias gcpa 'git cherry-pick --abort @args'
Bash-Alias gcpc 'git cherry-pick --continue @args'
Bash-Alias gd 'git diff @args'
Bash-Alias gdh 'git diff HEAD @args'
Bash-Alias gds 'git diff --staged @args'
Bash-Alias gdw 'git diff --word-diff @args'
Bash-Alias gg 'lazygit @args'
Bash-Alias ghkey 'gh ssh-key add ~/.ssh/id_ed25519.pub --title "$(hostname)" --type signing @args'
Bash-Alias ghpd 'pr_diff @args'
Bash-Alias ghpf 'pr_files @args'
Bash-Alias ghpr 'gh pr create @args'
Bash-Alias ghrc 'gh repo clone @args'
Bash-Alias ghrd 'gh repo edit -d @args'
Bash-Alias ghrh 'gh repo edit -h @args'
Bash-Alias ghro 'gh repo view --web @args'
Bash-Alias ghrr 'gh repo rename @args'
Bash-Alias ghrs 'gh release create @args'
Bash-Alias ghrt 'gh repo edit --add-topic  @args'
Bash-Alias ghrv 'gh repo edit --accept-visibility-change-consequences --visibility  @args'
Bash-Alias gl 'git pull --rebase --autostash @args'
Bash-Alias glog 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ad) %C(bold blue)<%an>%Creset" --date=short @args'
Bash-Alias glogf 'git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset" --stat @args'
Bash-Alias gmv 'git mv @args'
Bash-Alias gmx 'git merge -X ours @args'
Bash-Alias gp 'git push @args'
Bash-Alias gpF 'git push --force @args'
Bash-Alias gpf 'git push --force-with-lease --force-if-includes @args'
Bash-Alias grb 'git rebase @args'
Bash-Alias grba 'git rebase --abort @args'
Bash-Alias grbc 'git rebase --continue @args'
Bash-Alias grbi 'git rebase --interactive @args'
Bash-Alias grbo 'git rebase --onto @args'
Bash-Alias grbq 'git rebase --quit @args'
Bash-Alias greb 'git rebase --interactive --autostash --keep-empty --no-autosquash --rebase-merges main @args'
Bash-Alias grev 'git revert @args'
Bash-Alias greva 'git revert --abort @args'
Bash-Alias grevc 'git revert --continue @args'
Bash-Alias grH 'git reset --hard origin/main @args'
Bash-Alias grhh 'git reset --hard @args'
Bash-Alias grhk 'git reset --keep @args'
Bash-Alias grhs 'git reset --soft @args'
Bash-Alias grm 'git rm @args'
Bash-Alias grmc 'git rm --cached @args'
Bash-Alias gra 'git remote add @args'
Bash-Alias grrm 'git remote remove @args'
Bash-Alias grset 'git remote set-url origin git@github.com:user/repo.git @args'
Bash-Alias gsb 'git status --short --branch @args'
Bash-Alias gsd 'git status -s && git diff HEAD @args'
Bash-Alias gsv 'git status -v @args'
Bash-Alias gss 'git status -s @args'
Bash-Alias gst 'git status @args'
Bash-Alias gsh 'git show @args'
Bash-Alias gsta 'git stash push @args'
Bash-Alias gstaa 'git stash apply @args'
Bash-Alias gstall 'git stash --all @args'
Bash-Alias gstc 'git stash clear @args'
Bash-Alias gstd 'git stash drop @args'
Bash-Alias gstl 'git stash list @args'
Bash-Alias gstp 'git stash pop @args'
Bash-Alias gsui 'git submodule update --init --recursive @args'
Bash-Alias gsu 'git submodule update --remote --merge @args'
Bash-Alias gsuc 'git clone --recurse-submodules @args'
Bash-Alias gsus 'git submodule foreach "git status" @args'
Bash-Alias gsup 'git push --recurse-submodules=on-demand @args'
Bash-Alias gsm 'git switch main @args'
Bash-Alias gssm 'git stash push && git switch main @args'
Bash-Alias gsp 'git switch - @args'
Bash-Alias gsw 'git switch @args'
Bash-Alias gswc 'git switch --create @args'
Bash-Alias gtop 'cd "$(git rev-parse --show-toplevel)" @args'
Bash-Alias gwip 'git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign --message "--wip-- [skip ci]" @args'
Bash-Alias gwipe 'git reset --hard && git clean --force -df @args'
Bash-Alias e 'nvim $(fzf) @args'
Bash-Alias emd 'emacs --daemon & @args'
Bash-Alias emc 'emacsclient -c -a ''emacs'' @args'
Bash-Alias emt 'emacs --no-window-system @args'
Bash-Alias vi 'nvim @args'
Bash-Alias vg 'grep_open @args'
Bash-Alias vc 'changed_files @args'
Bash-Alias vr 'review_changes @args'
Bash-Alias vb 'binary_edit @args'
Bash-Alias me '"$EDITOR" README.md @args'
Bash-Alias alac '"$EDITOR" ~/.config/alacritty/alacritty.toml @args'
Bash-Alias alia '"$EDITOR" ~/.config/shell/aliases.sh @args'
Bash-Alias bashc '"$EDITOR" ~/.bashrc @args'
Bash-Alias enva '"$EDITOR" ~/.config/shell/environment.sh @args'
Bash-Alias malia '"$EDITOR" ~/.config/mac/aliases.sh @args'
Bash-Alias menva '"$EDITOR" ~/.config/mac/environment.sh @args'
Bash-Alias func '"$EDITOR" ~/.config/shell/functions.sh @args'
Bash-Alias gitc '"$EDITOR" ~/.gitconfig @args'
Bash-Alias kitc '"$EDITOR" ~/.config/kitty/kitty.conf @args'
Bash-Alias loca '"$EDITOR" ~/.config/shell/local.sh @args'
Bash-Alias nvimc 'nvim ~/.config/nvim/init.lua @args'
Bash-Alias p2k '"$EDITOR" "$ZDOTDIR/prompt/init.zsh" @args'
Bash-Alias qutc '"$EDITOR" ~/.config/qutebrowser/config.py @args'
Bash-Alias tmuxc '"$EDITOR" ~/.config/tmux/tmux.conf @args'
Bash-Alias vic 'nvim ~/.config/nvim/init.lua @args'
Bash-Alias vip 'nvim ~/.config/nvim/lua/plugins/list.lua @args'
Bash-Alias vimc 'vim ~/.vimrc @args'
Bash-Alias zshc '"$EDITOR" "$ZDOTDIR"/.zshrc @args'
Bash-Alias asc 'asciinema @args'
Bash-Alias cless 'colorize_less -N @args'
Bash-Alias cols 'spectrum_ls @args'
Bash-Alias exsu 'exercism submit @args'
Bash-Alias files 'fzf --preview ''bat --color=always --style=numbers --line-range=:500 {}'' @args'
Bash-Alias fix 'fuck @args'
Bash-Alias heic_to_jpg 'magick mogrify -format jpg *.HEIC @args'
Bash-Alias icat 'kitty +kitten icat @args'
Bash-Alias java8 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk/jre @args'
Bash-Alias java11 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/ @args'
Bash-Alias jupn 'jupyter notebook @args'
Bash-Alias kpa 'keepassxc-cli clip "$KEEPASS_DB" @args'
Bash-Alias mlc 'npx markdown-link-check -pvq @args'
Bash-Alias ncdu 'ncdu --color=dark -x @args'
Bash-Alias pick 'pastel pick | pastel format hex | ccp @args'
Bash-Alias png 'pngquant --ext .png --force @args'
Bash-Alias pp 'prettyping --nolegend @args'
Bash-Alias scr 'scrot -s -l width=3,color=''#1688f0'',mode=edge,opacity=75 -F ~/Pictures/Screenshots/snap-%Y-%m-%d-%H-%M-%S.png -e ''xclip -selection clipboard -t image/png -i ~/Pictures/Screenshots/snap-%Y-%m-%d-%H-%M-%S.png'' @args'
Bash-Alias scrf 'scrot -cd 3 -F ~/Pictures/Screenshots/snap-%Y-%m-%d-%H-%M-%S.png -e ''xclip -selection clipboard -t image/png -i ~/Pictures/Screenshots/snap-%Y-%m-%d-%H-%M-%S.png'' @args'
Bash-Alias scrw 'scrot -ubcd 3 -F ~/Pictures/Screenshots/snap-%Y-%m-%d-%H-%M-%S.png -e ''xclip -selection clipboard -t image/png -i ~/Pictures/Screenshots/snap-%Y-%m-%d-%H-%M-%S.png'' @args'
Bash-Alias serv 'npx live-server --port=1234 . @args'
Bash-Alias sto 'stackoverflow @args'
Bash-Alias tmux 'tmux -u @args'
Bash-Alias tmuxm 'tmux new-session \; split-window -h \; split-window -v \; attach @args'
Bash-Alias wit 'wiki-tui @args'
Bash-Alias xp 'xplr @args'
Bash-Alias ytdl 'youtube-dl @args'
Bash-Alias play 'playerctl play-pause @args'
Bash-Alias next 'playerctl next @args'
Bash-Alias prev 'playerctl previous @args'
Bash-Alias song 'playerctl metadata title @args'
Bash-Alias syslog 'sudo journalctl -b @args'
Bash-Alias logshare 'curl -F ''file=@-'' 0x0.st @args'
Bash-Alias esl 'yarn eslint --fix @args'
Bash-Alias eslx 'git diff --name-only main | grep -E "\.(js|jsx|ts|tsx)$" | xargs yarn eslint --fix @args'
Bash-Alias eslc 'git ls-files --modified --others --exclude-standard | grep -E "\.(js|jsx|ts|tsx)$" | xargs yarn eslint --fix @args'
Bash-Alias jst 'yarn jest --silent @args'
Bash-Alias jstx 'git diff --name-only main | grep -E "\.test\.(js|jsx|ts|tsx)$" | xargs yarn jest --silent @args'
Bash-Alias jstc 'git ls-files --modified --others --exclude-standard | grep -E "\.test\.(js|jsx|ts|tsx)$" | xargs yarn jest --silent @args'
Bash-Alias rcp 'bundle exec rubocop -A @args'
Bash-Alias rcpx 'git diff --name-only main | grep -E "\.(rb|rake)$" | grep -v "schema.rb" | xargs bundle exec rubocop -A @args'
Bash-Alias rcpc 'git ls-files --modified --others --exclude-standard | grep -E "\.(rb|rake)$" | grep -v "schema.rb" | xargs bundle exec rubocop -A @args'
Bash-Alias rsp 'bundle exec rspec @args'
Bash-Alias rspx 'git diff --name-only main | grep "_spec\.rb$" | xargs bundle exec rspec @args'
Bash-Alias rspc 'git ls-files --modified --others --exclude-standard | grep "_spec\.rb$" | xargs bundle exec rspec @args'
Bash-Alias rsc 'bundle exec rails console @args'
Bash-Alias rsv 'bundle exec rails server @args'
Bash-Alias jirv 'acli jira workitem view @args'
Bash-Alias jirp 'acli jira workitem search --jql "assignee = currentUser() and resolution = Unresolved order by updated desc" --fields "issuetype,key,priority,status,summary" @args'
Bash-Alias jirc 'acli jira workitem search --jql "assignee = currentUser() and resolution = Unresolved AND sprint in openSprints() order by updated desc" --fields "issuetype,key,priority,status,summary" @args'
Bash-Alias apti 'sudo apt install @args'
Bash-Alias apts 'apt search @args'
Bash-Alias aptr 'sudo apt remove @args'
Bash-Alias aptq 'apt show @args'
Bash-Alias aptu 'sudo apt update && sudo apt upgrade @args'
Bash-Alias dnfi 'sudo dnf install @args'
Bash-Alias dnfs 'dnf search @args'
Bash-Alias dnfr 'sudo dnf remove @args'
Bash-Alias dnfu 'sudo dnf update @args'
Bash-Alias npi 'npm install @args'
Bash-Alias npr 'npm run @args'
Bash-Alias paci 'sudo pacman -S @args'
Bash-Alias pacq 'pacman -Qi @args'
Bash-Alias pacr 'sudo pacman -Rsc @args'
Bash-Alias pacR 'pacman -Qdtq @args'
Bash-Alias pacs 'pacman -Ss @args'
Bash-Alias pacl 'pacman -Q @args'
Bash-Alias pacm 'sudo pacman-mirrors --fasttrack 5 && sudo pacman -Syu @args'
Bash-Alias pacu 'sudo pacman -Syu @args'
Bash-Alias yayi 'yay -S @args'
Bash-Alias yayl 'pacman -Qm @args'
Bash-Alias yayu 'yay -Syu @args'
Bash-Alias aran 'autorandr -l @args'
Bash-Alias blue 'bluetuith @args'
Bash-Alias litu 'sudo light -A 10 @args'
Bash-Alias litd 'sudo light -U 10 @args'
Bash-Alias plasmar 'kquitapp5 plasmashell && kstart5 plasmashell @args'
Bash-Alias shad 'ssh-add ~/.ssh/id_rsa @args'
Bash-Alias shag 'eval "$(ssh-agent -s)" @args'
Bash-Alias sysd 'sudo systemctl disable @args'
Bash-Alias syse 'sudo systemctl enable @args'
Bash-Alias sysr 'sudo systemctl restart @args'
Bash-Alias syss 'systemctl status @args'
Bash-Alias systa 'sudo systemctl start @args'
Bash-Alias systo 'sudo systemctl stop @args'
Bash-Alias topg 'topgrade --no-retry -y @args'
Bash-Alias topG 'topgrade --no-retry -y --only git_repos @args'
Bash-Alias vol 'pulsemixer @args'
Bash-Alias volu 'amixer sset ''Master'' 10%+ @args'
Bash-Alias vold 'amixer sset ''Master'' 10%- @args'
Bash-Alias wifi 'nmtui @args'
